# Generated by Django 4.2.dev20220624125221 on 2022-09-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_ID', models.CharField(max_length=7)),
                ('EVENT_ID', models.CharField(max_length=100)),
                ('PAYMENT_DETAILS', models.CharField(max_length=30)),
                ('PAYMENT', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DonatorTable',
            fields=[
                ('D_ID', models.CharField(max_length=7)),
                ('EMAIL', models.EmailField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FundTable',
            fields=[
                ('EVENT_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('COLLECTED_AMOUNT', models.IntegerField()),
                ('FUND_STATUS', models.CharField(max_length=20)),
                ('FUND_TAKEN_BY', models.CharField(max_length=100)),
            ],
        ),
    ]
