# Generated by Django 4.2.dev20220624125221 on 2022-09-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EVENT_NAME', models.CharField(max_length=80)),
                ('START_TIME', models.DateField()),
                ('END_TIME', models.DateField()),
                ('LOCATION', models.CharField(max_length=40)),
                ('BUDGET', models.IntegerField()),
                ('SHOP', models.CharField(max_length=50)),
                ('ITEMS', models.CharField(max_length=40)),
                ('QUANTITY', models.IntegerField()),
                ('EVENT_FOR', models.CharField(max_length=80)),
                ('CREATED_BY', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizorTable',
            fields=[
                ('O_ID', models.CharField(max_length=7)),
                ('EMAIL', models.EmailField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHOP_NAME', models.CharField(max_length=80)),
                ('PAY_DEMAND', models.CharField(max_length=20)),
                ('DELIVERY_STATUS', models.CharField(max_length=50)),
            ],
        ),
    ]
