# Generated by Django 4.2.dev20220624125221 on 2022-09-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTable',
            fields=[
                ('V_ID', models.CharField(max_length=7)),
                ('EMAIL', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('STATUS', models.CharField(max_length=20)),
                ('VOLUNTARY', models.CharField(max_length=100)),
            ],
        ),
    ]
